name: Express API Build and Deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - run: npm ci
    - run: npm test
    
  push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        node-version: [18.x] # Version what its going to be done before push
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Setup commit sha
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 7

      - name: Build non-master
        run: docker build --tag users:${{ steps.short-sha.outputs.sha }} .

      - name: Build main
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        uses: jwalton/gh-ecr-push@v1
        env:
          REGISTRY: 232187837350.dkr.ecr.us-east-1.amazonaws.com
          IMAGE: users
          SHA: ${{ steps.short-sha.outputs.sha }}
          REF: ${{ github.ref }}
          ISMASTER: ${{ github.ref == 'main' }}
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          image: ${{env.IMAGE}}:${{ env.SHA }}
